# Spec for singla A100 40GB

data_remote: # If blank, files must be present in data_local
data_local: /data/tl-prd-rwde-model-dev/ktlm_ocr_corpus/ocr_pages_filtered_v1_0_0/mosaic
tokenizer_name: bert-base-uncased
max_seq_len: 4096
text_column: content_normed
mlm_probability: 0.15 # Mosaic BERT should use 30% masking for optimal performance

# Run Name
run_name: hf-bert-page-E768-L12-H12-P4096-bert-base-uncased-tempus-v32k

# Model
model:
  name: hf_bert
  use_pretrained: false # Train the model from scratch. Set to true to start from the HF off-the-shelf weights.
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  # Mosaic BERT 'base' generally uses the default architecture values for from the
  # Hugging Face BertConfig object
  # Note: if using the pretrained_checkpoint argument to create a model from an
  # existing checkpoint, make sure the model_config settings match the architecture
  # of the existing model
  model_config:
    num_attention_heads: 12 # bert-base default
    num_hidden_layers: 12 # bert-base default
    attention_probs_dropout_prob: 0.1 # bert-base default

# Dataloaders
train_loader:
  name: text
  dataset:
    remote: ${data_remote}
    local: ${data_local}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    text_column: ${text_column}
    predownload: 1000
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    remote: ${data_remote}
    local: ${data_local}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    text_column: ${text_column}
    predownload: 1000
    shuffle: false
    mlm_probability: 0.15 # We alwayas evaluate at 15% masking for consistencey
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration

optimizer:
  name: decoupled_adamw
  lr: 5.0e-4
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5

algorithms:
  fused_layernorm: {}

# Training duration and evaluation frequency
max_duration: 1ep
eval_interval: 2ep
global_train_batch_size: 4096

# System
seed: 17
device_eval_batch_size: 32
device_train_microbatch_size: 32
precision: amp_bf16

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba
log_file: /data/tl-prd-rwde-model-dev/ktlm_mosaic_models/${run_name}/file_logs/log.txt
tensorboard_log_dir: /data/tl-prd-rwde-model-dev/ktlm_mosaic_models/${run_name}/tensorboard_logs

callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

# (Optional) Checkpoint to local filesystem or remote object store
save_interval: 500ba
save_num_checkpoints_to_keep: 3  # Important, this cleans up checkpoints saved to DISK
save_folder: /data/tl-prd-rwde-model-dev/ktlm_mosaic_models/${run_name}/ckpt
